#!/bin/bash
# Set up the workbench server
# Note - must be run a root, which is the case when run using user-data/cloud init

# Mount EFS over /home. This holds all my workbooks
mount -t nfs4 -o nfsvers=4.1 us-west-2a.fs-fa54a053.efs.us-west-2.amazonaws.com:/ /home

# update my tools directories
cd ~/bin
git pull

cd ~/IPython-notebook-extensions/
git pull

#setup sydney timezone
rm -f /etc/localtime
ln -s /usr/share/zoneinfo/Australia/Sydney /etc/localtime

# Setup and run jupyter notebook server
cd ~ec2-user/bin
cp jupyter.init.d /etc/init.d/jupyter
service jupyter start

# Upate DNS to point workbench URL to this server
./update-route53-dns

yum update -y
yum install git iotop -y

echo Done
