#!/bin/bash +x
# Set up the workbench server
# Note - must be run a root, which is the case when run using user-data/cloud init

exec > /tmp/initalise.log  2>&1
echo "Configurting instance"
date

# Mount EFS over /home. This holds all my workbooks
mount -t nfs4 -o nfsvers=4.1 $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-fa54a053.efs.us-west-2.amazonaws.com:/ec2-user/Notebooks /home/ec2-user/Notebooks

# Mount graphlab tmp director on EFS to avoid running of space
mount us-west-2b.fs-fa54a053.efs.us-west-2.amazonaws.com:/tmp /var/tmp/
# Setup and run jupyter notebook server
service jupyter start

yum update -y
yum install git iotop -y

# Upate DNS to point workbench URL to this server
/home/ec2-user/bin/update-route53-dns

echo Done
