#!/bin/bash
#
#source activate dato-env > ~/.jupyter//jupyter.log 2>&1

nohup jupyter notebook --NotebookApp.port=8888 --no-browser --ip='*' --notebook-dir=/home/ec2-user > ~/.jupyter//jupyter.log 2>&1 &
echo $! > ~/.jupyter/jupyter.pid

