#!/bin/bash
#
#source activate dato-env > ~/.jupyter//jupyter.log 2>&1

export PATH=/home/ec2-user/anaconda2/bin:$PATH
nohup jupyter notebook > ~/.jupyter//jupyter.log 2>&1 &
echo $! > ~/.jupyter/jupyter.pid

