#!/bin/sh 

# Make sure only root can run our script                
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi
PATH=$PATH:/opt/aws/bin
# Load configuration
. /etc/route53/config

# Export access key ID and secret for cli53
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY

# Use command line scripts to get instance ID and public hostname
#INSTANCE_ID=$(ec2-metadata | grep 'instance-id:' | cut -d ' ' -f 2)
PUBLIC_HOSTNAME=$(ec2-metadata | grep 'public-hostname:' | cut -d ' ' -f 2)
PUBLIC_HOSTNAME+="."
HOST_NAME=`hostname -s`

# Create a new CNAME record on Route 53, replacing the old entry if nessesary
#echo cli53 rrcreate --replace "$ZONE" "$HOST_NAME 60 CNAME $PUBLIC_HOSTNAME" 
cli53 rrcreate --replace "$ZONE" "$HOST_NAME 60 CNAME $PUBLIC_HOSTNAME" 
