#!/bin/sh 

PATH=$PATH:/opt/aws/bin

# Export access key ID and secret for cli53
#export aws_access_key_id="AKIAIVLXXUIOZUTWM7FQ"
#export aws_secret_access_key="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"
export ZONE="datascienceinstitute.com.au"
export TTL="600"

# Use command line scripts to get instance ID and public hostname
#INSTANCE_ID=$(ec2-metadata | grep 'instance-id:' | cut -d ' ' -f 2)
PUBLIC_HOSTNAME=$(ec2-metadata | grep 'public-hostname:' | cut -d ' ' -f 2)
PUBLIC_HOSTNAME+="."
HOST_NAME=jupyter1

# Create a new CNAME record on Route 53, replacing the old entry if nessesary
/home/ec2-user/bin/cli53 rrcreate --replace "$ZONE" "$HOST_NAME 300 CNAME $PUBLIC_HOSTNAME" 
logger "ROUTE53: Setting DNS CNAME $MY_NAME.$ZONE to $PUBLIC_HOSTNAME"

